packages:
  - "apps/*"
  - "libs/*"
strictPeerDependencies: false
shamefullyHoist: false
allowBuilds:
  "@parcel/watcher": true
  unrs-resolver: true
  "electron-winstaller": true
  esbuild: true
  nx: true
